config/routes.rb
Rails.application.routes.draw do
root 'souvenirs#index'

get '/post',   to: 'souvenirs#new'
get  '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'
resources :souvenirs
resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/souvenir.rb
class Souvenir < ApplicationRecord
    belongs_to :user
    #画像のアップローダー
    mount_uploader :picture ,PictureUploader
    #存在性のvalidation
    validates:name, presence: true,length: {maximum:70}
    validates:comment, presence: true,length: {maximum:250}
    validates:spot, presence: true
    validates:price, presence: true
    validates:genre, presence: true
    validate :picture_size

    private
    #画像サイズのバリデーション
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

    def souvenir_params
      params.require(:souvenirs).permit(:name, :spot, :price, :genre, :picture, :comment)
    end
  

end

app/models/user.rb
class User < ApplicationRecord
    has_many :souvenirs
    attr_accessor :remember_token
    before_save   :downcase_email
    validates :name, presence:true, length: {maximum: 70}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

#beforeフィルター
    #users & souvenirs controller
    def already_logged_in
        unless logged_in?
            flash[:danger] = "ログインしてください"
            redirect_to login_url
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  
  end

  def create
  user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      flash[:success] = "ログインに成功しました"
      redirect_to user
    else
      flash.now[:warning] = "ログインに失敗しました。"
      render 'new'
    end
  end

  def destroy
    logout
    flash[:info] = "ログアウトしました"
    redirect_to root_url

  end
end

app/controllers/souvenirs_controller.rb
class SouvenirsController < ApplicationController

  before_action :set_souvenir_params, only: [:show, :edit, :update, :destroy]
  before_action :already_logged_in, only: [:create, :edit, :update, :destroy]
  def new
    @souvenir = Souvenir.new
    flash[:info] = "項目を記入してください"
  end

  def index
    @souvenirs = Souvenir.paginate(page: params[:page], per_page: 5)
  end

  def create
    @souvenir = current_user.souvenirs.build(souvenir_params)
      if @souvenir.save
        flash[:success] = "投稿に成功しました"
        redirect_to action: 'index'
      else
        render 'new'
      end
  end

  def show
  end

  def edit
  end

  def update
    if @souvenir.update(souvenir_params)
      flash[:success] = "編集に成功しました"
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end
  
  def destroy
    @souvenir.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

  def souvenir_params
    params.require(:souvenir).permit(:name, :spot, :price, :picture, :genre, :comment)
  end

  def set_souvenir_params
    @souvenir = Souvenir.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]
  before_action :already_logged_in, only: [:edit, :show, :update, :destroy]
  def index
    @users = User.all
  end

  def show
    @souvenirs = @user.souvenirs.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザー登録に成功しました"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = "編集に成功しました"
      redirect_to action: 'index'
    else
      render 'show'
    end

  end

  def destroy
    @user.destroy
    flash[:success] = "削除に成功しました"
    redirect_to  root_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def login(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def logout
        session.delete(:user_id)
        @current_user = nil
      end

end

app/helpers/souvenirs_helper.rb
module SouvenirsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <%= link_to "トップページへ", root_path %>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-expand-md  navbar-light bg-light">
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#bs-navi" aria-controls="bs-navi" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="bs-navi">
      <%= link_to "おみやげ Picker", root_path, id: "logo" %>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to "ホーム", root_path, class:"nav-link" %></li>
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "投稿", post_path, class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "myページ", user_path(current_user), class:"nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", logout_path, class:"nav-link" %></li>
        <% else%>
          <li class="nav-item"><%= link_to "ログイン", login_path, class:"nav-link" %></li>     
        <% end %> 
    </ul>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PickerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_common_form.html.erb
<%= form_for(souvenir) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

　　<%= f.label :name %>
    <%= f.text_field:name %>

　　<%= f.label :spot %>
    <%= f.text_field:spot %>

　　<%= f.label :price %>
    <%= f.text_field:price %>

　　<%= f.label :picture %>
　　<%= f.file_field :picture %>

　　<%= f.label :genre %>
    <%= f.select :genre, [ ["ごはん","food"], ["飲み物","drink"], ["雑貨","goods"] ] %>

　　<%= f.label :comment %>
　　<%= f.text_area :comment %>

    <%= f.submit %>

<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">入力内容に<%= object.errors.count%>箇所の不備が存在します</div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

app/views/shared/_souvenir.html.erb
<%= link_to souvenir_path(souvenir) do  %>
<div class = "row souvenir_box">
    <div class = "souvenir_name col-sm-12"><%= souvenir.name%></div>
        <div class = "col-sm-7">
            <div class="row">
                <div class = "souvenir_spot col-sm-12 souvenir_text-items ">場所：<%= souvenir.spot%></div>
                <div class = "souvenir_price col-sm-12 souvenir_text-items">値段：<%= souvenir.price%></div>
                <div class = "souvenir_genre col-sm-12 souvenir_text-items">ジャンル：<%= souvenir.genre%></div>
            </div>
        </div>
        <div class = "col-sm-4">  
        <% if souvenir.picture? %>
        　　<%= image_tag souvenir.picture.thumb.url %>
        　<% else %>
            <p>noimages</p>
        <% end %>
        </div>
        

    <div class = "col-sm-12 souvenir_text-items">コメント：<%= souvenir.comment%></div>
</div>
<% end %>

app/views/souvenirs/edit.html.erb
<div id = "edit">
    <%= render partial:"shared/common_form", locals: {souvenir: @souvenir} %> 
</div>

app/views/souvenirs/index.html.erb
<div id = "index">
    <%= will_paginate  @souvenirs %>
            <%= render partial:"shared/souvenir", collection: @souvenirs %> 
    <%= will_paginate  @souvenirs %>
</div>

app/views/souvenirs/new.html.erb
<div id = "new">
    <%= render partial:"shared/common_form", locals: {souvenir: @souvenir} %> 
</div>

app/views/souvenirs/show.html.erb
<div id = "s_show">
    <%= render partial:"shared/souvenir", locals: {souvenir: @souvenir} %> 
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

　　<%= f.label :名前 %>
    <%= f.text_field:name ,class: "form_item"%>

　　<%= f.label :Eメール %>
    <%= f.email_field:email ,class: "form_item"%>

    <%= f.label :あなたのパスワード %>
    <%= f.password_field :password ,class: "form_item"%>

    <%= f.submit %>

<% end %>

app/views/users/new.html.erb
<h1>ユーザー新規登録</h1>
<%= render partial:'form', locals: {user: @user} %>

app/views/users/show.html.erb
<div id = "u_show">
    <div class = "row">
        <div class = "col-sm-4">
            <section class="user_info">
                <h3 class = "user_name">
                    <%= @user.name %>
                </h3>
                <h3>ユーザー登録情報変更</h3>
                <p class = "edit_alert">項目を編集後<br>Update Userボタンを押してください</p>
                <%= render partial:"form", locals: {user: @user} %> 
            </section>
        </div>
        <div class = "col-sm-8">
            <section class="user_souvenirs">
                <% if @user.souvenirs.any? %>
                    <%= will_paginate  @souvenirs %>
                        <%= render partial:"shared/souvenir", collection: @souvenirs %> 
                        <%= link_to "投稿内容の編集", edit_souvenir_path %>
                    <%= will_paginate  @souvenirs %>
                    
                <% else %>
                    <p>初めての投稿をしてみませんか？</p>
                    <button type="button" class="btn btn-info"><%= link_to "おすすめのお土産を投稿する",new_souvenir_path %></button>
                <% end %>
            </section>
        </div>
    </div>
</div>